### ISSUE TITLE
Separate Function Keys

### ISSUE THREAD

**Issue by fruitofgeorge** [alberti42/iTunes-Volume-Control#20]
First, thanks for making this. I've been searching for a solution and it's great to finally find it in a neat little app.
I just have a suggestion for added functionality. Sometimes I play spotify music in the background and then have other sound sources playing as well, like youtube in a browser for example. It would be great to add a keyboard shortcut to control system volume while spotify is also playing. I'm thinking keep normal operation of volume up/down keys controlling spotify but adding a modifier or function key to volume up/down keys for system volume.

**Comment by alberti42** [comment]
Thank you for the suggestion. This feature is already there. Have you tried to change the volume holding the apple key modifier? This modifier changes the standard behaviour so that if you normally control iTunes volume, then with the modifier you control the system volume, and vice versa, if you selected the option to use the modifier to control iTunes’ volume.

**Comment by fruitofgeorge** [comment]
Oh cool. I didn't see that in any documentation. That's a pretty big feature to leave out of the readme. I guess the only thing I could wish for more would be the step size to effect both modified and unmodified volumes but it's pretty great as is. Thanks!
